# Generated by Django 4.1.2 on 2023-02-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='projects/images/')),
                ('url', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('WD', 'Web Development'), ('VE', 'Video Editing'), ('DG', 'Design')], default='WD', max_length=2)),
            ],
        ),
    ]
