# Generated by Django 4.1.2 on 2023-02-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='homepage/images/explogos/')),
                ('url', models.URLField(blank=True)),
                ('fromdate', models.DateField()),
                ('todate', models.DateField()),
            ],
        ),
    ]
