# Generated by Django 4.1.2 on 2023-02-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exp',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
